version: "3.5"
services:
    m1:
        image: boost-mpi-example
        #network_mode: host
        ports:
            - "7657:7657"

    m2:
        image: boost-mpi-example
        volumes:
            - .:/code
        ports:
            - "8001:8001"
        expose:
            - "8001"

    m3:
        image: boost-mpi-example
        ports:
            - "5433:5433"
        expose:
            - "5433"
        #volumes:
        #    - ./db_init/:/docker-entrypoint-initdb.d
